site_name: UCCSER Documentation
site_author: UCCSER
# site_url:
copyright: This content is licensed under Creative Commons Attribution-ShareAlike 4.0 International license (CC-BY-SA-4.0).
repo_url: https://github.com/uccser/uccser.github.io
theme:
  name: readthedocs
  custom_dir: overrides
nav:
    - Home: index.md
    - Contribution Documentation:
        - contribution-documentation/mission.md
        - Code of Conduct: https://github.com/uccser/.github/blob/master/CODE_OF_CONDUCT.md
        - contribution-documentation/projects.md
        - Contributing Guide: https://github.com/uccser/.github/blob/master/CONTRIBUTING.md
    - Technical Documentation:
        - technical-documentation/installation-guide.md
        - technical-documentation/technical-stack-structure.md
        - technical-documentation/internationalisation.md
        - technical-documentation/branching-strategy.md
        - technical-documentation/content-style.md
        - technical-documentation/programming-style.md
        - technical-documentation/licencing.md
        - technical-documentation/term-definitions.md
    - Staff Documentation:
        - staff-documentation/getting-started.md
        - staff-documentation/communication.md
        - staff-documentation/file-storage.md
        - staff-documentation/issue-management.md
        - staff-documentation/student-projects.md
    - Useful Links:
        - GitHub: https://github.com/uccser
        - Slack: https://deptfunstuff.slack.com
        - Twitter: https://twitter.com/UCCSEd
